import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'creator_notes';

  options =[
    '1. [] Mensaje PC: Se presentaron errores en la expedición del cambio de la póliza',
'2. Afectación core GW',
'3. Ajuste Declaracion final',
'4. Asesor no registra en la oficina para traspasos de cartera',
'5. Attempt to access bean of type "PolicyPeriod"',
'6. Campo huérfano "PolicyAddlInterest" ',
'7. Cancelación desde inicio de vigencia ',
'8. Cierre Transacción',
'9. Claims no trae la vigencia anterior de póliza ',
'10. Cobros flotantes',
'11. Consulta de modificación con estado "Error de Datos"',
'12. Corregir tasa',
'13. Operación en estado Nuevo/Pendiente/Vencido',
'14. Database bean version conflict ',
'15. Debe existir al menos un asegurado para los artículos de los riesgos',
'16. Dto Validation',
'17. Duplicate key',
'18. Effective windows of bean overlaps',
'19. El asesor no se encuentra inscrito en una oficina Gran Empresa',
'20. El complemento de reaseguro no puede recuperar…',
'21. El Contacto tiene un rol Interés adicional duplicado',
'22. El CustomId para la operación Cancelación está asociado a una operación diferente',
'23. El deducible porcentual seleccionado en dinero se encuentra por fuera de políticas y requiere autorización',
'24. El estado de la operación no es válido, se debe volver a iniciar el proceso de tarifación',
'25. El grupo de coberturas tiene la marca de reaseguro especial y Requiere aprobación del negocio',
'26. El grupo no existe - Oficinas',
'27. El número de la póliza ingresada no existe',
'28. El número de póliza no corresponde al tipo de operación de la auditoría',
'29. El período no esta en un estado válido para rehabilitar',
'30. El periodo para realizar la declaración de la auditoría aún no está habilitado',
'31. El porcentaje total de participación de los tomadores debe ser 100',
'32. El producto de la póliza no esta activo para la migración',
'33. El resultado de la expedición es inconsistente',
'34. El Tipo de Dirección DIRECCION DE OFICINA PRINCIPAL no es válido…',
'35. El Tipo de Dirección DIRECCION DE RESIDENCIA no es válido….',
'36. El tomador principal no tiene actividad económica',
'37. El valor asegurado no puede ser cero o nulo',
'38. El valor de la coordenada X, Y, y ZonaSismica no es un valor numérico',
'39. Encolamiento BC/SAP',
'40. Encolamiento PC/BC',
'41. Error actualizando los datos',
'42. Error al tarifar',
'43. Error al tratar de cambiar moneda',
'44. Error cambiando plan de facturación',
'45. Error cambio de asesor',
'46. Error cancelacion master vs riesgos',
'47. Error cancelación por no pago',
'48. Error cargando los datos de la oferta',
'49. Error consultando los periodos pagos',
'50. Error consultando riesgos',
'51. Error de comisiones en las renovaciones ',
'52. Error ejecutando la rutina, no es posible generar prima',
'53. Error en PDF / Cotización-Carátula-Documentos',
'54. Error en PDF / Facturas-Recibos-Cobros',
'55. Error inclusión riesgo',
'56. Error null en cotización',
'57. Error prima en modificación valorable',
'58. Error tarifa',
'59. Errores consultando la transacción',
'60. Errores de validación en el campo: company.comercialName',
'61. Estados inconsistentes ',
'62. Existe un acuerdo facultativo proporcional asociado al grupo de coberturas Fraude',
'63. Existen ofertas sin riesgos asociados',
'64. Existen transacciones sin expedir',
'65. Falta de artículos para finalizar modificación',
'66. Falta el codigo de la ciudad de la sedes para Propiedad',
'67. Faltan campos en la solicitud',
'68. Fecha no permite modificar',
'69. Ha ocurrido un error consultando los periodos pagos y facturados ',
'70. Ha ocurrido un error en el servicio de validación del Sarlaft',
'71. Hubo un error actualizando los datos',
'72. Java.lang NullPointerException',
'73. Actividad Económica NO es asegurable',
'74. Actividad Económica NO parametrizada.',
'75. La búsqueda no devolvió resultados.',
'76. La comisión ingresada para la solución supera lo permitido',
'77. La edad de la mascota no permite ser actualizada',
'78. La fecha de expiración no puede ser igual a la fecha de vigencia',
'79. La información de asesor y oficina no es válida',
'80. La póliza es de TRE y sólo tiene coberturas de trayecto exterior y no se puede identificar si corresponde a una importación o exportación',
'81. La póliza no puede ser cancelada con el motivo "Por no pago"',
'82. Claúsulas: Línea de Responsabilidad Civil - Claúsula de Compensación',
'83. Se presentaron errores en la cotización de la renovación de póliza',
'84. Se presentaron errores en la expedición de la renovación de póliza',
'85. Model Name: Failure rate increase on Web request service Service_ms-ohs-autos.jar',
'86. Model Name: Service_co.com.sura.seus.authorization.Main seus-authorization',
'87. Modelo de autorizaciones',
'88. Modificación no valorable genera cobro',
'89. Modificación genera control de paz y salvo pero en requisitos no aparece',
'90. Modificación genera error de reaseguro',
'91. Modificacion solicita requisitos pero no existen',
'92. Modificar forma de pago',
'93. Modificar plan de mora',
'94. Modificar tomador',
'95. Na hay informacion del cuentahabiente',
'96. No aparece un plan de asistencia',
'97. No genera factura en SAP',
'98. No carga, ver resultado de tarifación',
'99. No cargan los controles',
'100. No copia acuerdo facultativo de reaseguro a los demás riesgos',
'101. No despliega la información del producto',
'102. No es posible cargar la información del prospecto',
'103. No es posible conectarse a verificar la información en riesgos',
'104. No es posible continuar con el envio de la solicitud electronica, hay una solicitud en proceso',
'105. No es posible migrar/renovar la poliza genera error: edge.jsonrpc.exception.JsonRpcInternalErrorException: nullnull',
'106. No existe el valor tipo valor asegurable',
'107. No existe tomador principal para la operación',
'108. No existe typelist typekey.Country',
'109. No existe typelist typekey.PrimaryPhone',
'110. No existe una oficina seleccionada para la póliza',
'111. No existen riesgos asociados',
'112. No fue posible redistribuir la prima comercial aplicada',
'113. No genera factura en BC',
'114. No habilita boton para ajustar tasa ',
'115. No habilita campo (Ciudad) en informacion de la Sedes',
'116. Coberturas - No habilita las coberturas',
'117. No hay información sobre el valor asegurado por grupo, por lo que no es posible redistribuirlo',
'118. No hay reaseguro para el Job',
'119. No hay requisito pendiente para generar carta de cancelación',
'120. No permite cancelar poliza',
'121. No permite editar la operación',
'122. No permite hacer exclusión del modulo fraude',
'123. No permite ingresar al resultado',
'124. No permite levantar control',
'125. No se creo grupo tarifario',
'126. Coberturas - No despliega las coberturas',
'127. No se encontró póliza en el sistema de facturación',
'128. No se genera el proceso de cancelación',
'129. No se habilita la información del producto',
'130. No se habilitan los campos para la modificación',
'131. Sucursal esta bloqueada',
'132. No se puede agregar transporte de mercancía específico',
'133. No se puede comprometer el periodo de la póliza debido a un reaseguro no válido',
'134. No se puede continuar con la operación dado que no se encontraron parámetros para validar políticas',
'135. No se puede cotizar una póliza CP sin artículos ',
'136. No se puede ingresar módulos o artículos flotantes',
'137. No se puede redistribuir sin cotizar',
'138. Coberturas - No tiene coberturas obligatorias',
'139. No tiene un programa de reaseguro activo',
'140. No toma el ajuste tarifario',
'141. La cobertura no tiene reaseguro - Obj. ReserveSet',
'142. Ocurrió un error realizando el proceso de reextracción',
'143. Operación expedida con errores',
'144. PDF NO Descarga / Envía',
'145. Pérdida de información',
'146. Información incorrecta',
'147. Período de cobro errado',
'148. PLANTILLA ARUS_INC_GE_PROC',
'149. PLANTILLA ARUS_INC_GE_TEST',
'150. Póliza nueva no habilita para incluir coberturas ni cotizar',
'151. Procesamiento Masivo',
'152. Prorroga genera valor',
'153. Claúsulas: Transporte - Anexo Mercancias a Granel --  Adicionar - Actualizar',
'154. Rehabilitando la póliza y salió para riesgos consultables',
'155. Renovación no permite ingresar la tasa',
'156. Renovación no toma los deducibles ',
'157. Renovación trae producto incorrecto',
'158. Requiere reaseguro especial',
'159. Reservar ajuste',
'160. result.policyInfo',
'161. Revisión de facturación',
'162. Riesgos duplicados',
'163. Se detectaron una o más violaciones de restricciones nulas para EffectiveDatedFields',
'164. Se detectaron una o más violaciones de restricciones nulas para PaymentInstrument',
'165. Se devuelve al dashboard',
'166. Se está modificando pero al dar guardar información está no guarda los cambios',
'167. Se presentaron errores consultando la información de contactos',
'168. Se presentaron errores de concurrencia en la cotización de la póliza',
'169. Se produjo un error al crear un periodo de póliza a partir del periodo actual ',
'170. Se produjo un error al descargar/cargar archivo masivo',
'171. Se requiere el valor "Tipo deducible mínimo"',
'172. Se requiere el valor "Tipo valor asegurado" de la condición de cobertura',
'173. Solicitud cancelación de la póliza en TRE',
'174. Solicitud Nota Manual - Débito/Crédito',
'175. Supera el límite del programa de reaseguro',
'176. Termina con errores',
'177. Traspaso de Cartera',
'178. Transacción en proceso / Tarifación-Expedición-Cancelación',
'179. Validar Comisión ',
'180. Vigencia fecha futura',
'181. Ya existe una cotización para el cliente',
'182. Ya se usó el número de acuerdo',
'183. You cannot change a locked branch',
'184. La póliza ha sido pagada hasta la fecha XXXX por lo tanto ésta es la fecha máxima de cancelación permitida',
'185. Ha ocurrido un error interno en la aplicación consultando la fecha de financiación SIF',
'186. No hay periodo para esta fecha de vigencia',
'187. Devolución errada',
'188. Capacitación Aplicativo',
'189. Capacitación Negocio',
'190. No se pudo tomar la medida edit por las razones siguientes: Tiene un flujo de proyecto de renovación activo',
'191. Ocurrió un error al consultar la idoneidad del usuario o asesor para la solución',
'192. Reaseguro Aceptación especial - Capacidad adicional',
'193. No se puede cambiar PeriodStart salvo que EditEffectiveDate coincida con PeriodStart actual',
'194. Riesgos pierden el estado de expedido',
'195. Acuerdos facultativos duplicados',
'196. Claúsulas: Condiciones Generales - Línea de propiedades comerciales',
'197. Grupo de Categoria - Grupo No Existe - Es Obligatorio',
'198. No hay un periodo en vigor para la póliza xxxxxxxxxxxx en la fecha xx de xxxxxxxx de xxxx',
'199. Java.lang.NumberFormatException',
'200. Java.lang.RuntimeException',
'201. No fue posible generar los documentos',
'202. No permite descargar documento',
'203. No fue posible descargar el documento en línea',
'204. No envia Documentación a correo ',
'205. Al menos una figura requiere información adicional en el Sarlaft',
'207. No se visualiza el valor de coberturas en PDF de renovación de mascotas',
'208. El ID XXXX para la operación Renovación está asociado a una transacción con estado Retirado',
'209. El valor XXXX no tiene el formato correcto para el campo "value"',
'210. Los requisitos ya fueron gestinados pero continúa solicitandólos',
'211. La cotización tiene reaseguro especial, por lo tanto, se debe realizar nuevamente el proceso de financiación',
'212. Error null en evaluación',
'213. java lang IllegalArgumentException',
'214. El documento de identidad no cumple con el formato',
'215. Error en la proforma del slip',
'216. Error cargando datos de los asegurados / beneficiarios',
'217. Modificación valorable no genera cobro',
'218. Vigencia errada',
'219. Sharefile -  P8',
'220. No hay una TRM configurada en el plugin FXRate',
'221. No se puede comprometer una póliza sin haber elegido un plan de pagos',
'222. Eror aumento en la capacidad económica en pólizas expedidas con reaseguro',
'223. Error en tasas al crear el reaseguro especial',
'224. Ocurrió un error en el proceso de evaluación: /u01/escritura_12.1.3/guidewire/tablasParametros/AnnualMobilizationBudget.csv',
'225.Ocurrió un error en el proceso de evaluación: Division undefined Mensaje PC: Se presentaron errores en la cotización del cambio de la póliza',
'226. El código del reasegurador no se encuentra activo',
'227. El grupo de coberturas Auto Liability no tiene un programa de reaseguro activo',
'228. El cliente realizó cambio de asegurado pero en los cobros posteriores sigue registrando el asegurado anterior- Actualizar asegurado para un riesgo',
'229. Ingresar a morosidad la vigencia sin pagar. -Ingresar una poliza a mora',
'230. Se revierte el periodo de auditoria para generar el valor de la devolución correspondiente. ',
'231.  Los recibos de facturación se generan con error en el periodo de cobro',
'232. Se superó la cantidad máxima de cambios para el día de facturación. ',
'233. Actualizar o cambiar el asegurado de un riesgo',
'234. Ajustar periodo de cobro de una factura',
'235. No es posible cambiar el plan de facturación por parte del usuario. ',
'236. Se crea range de facturación para los riesgos pendientes (ISSUANCE y CANCELLATION)',
'237. Valor de IVA invalido',
'238. Bloquear periodo e Iniciar auditoria para que el movimiento se facture',
'239. Duplicidad en Cobros en BC',
'240. Error: Reclamo Comisiones Pagadas por mayor valor',
'241. java. lang. IllegalStateException: This is a left value',
'242. Tarifa vs PDF',
'243. No se logro establecer el id con el objeto asegurable',
'244. El grupo de coberturas del riesgo xxx deben tener colocación facultativa',
'245. Fuera de secuencia en modificaciones',
'246. Bucle Infinito - Tarifación',
'247. Error guardando la inf... No debe tener periodicidad sin el tipo de modalidad',
'248. La renovacion de la poliza aun no se ha actualizado en vinculaciones',
'249. Existen ofertas sin honorarios obligatorios',
'250. Grupo de Categoria - Número de camas es obligatorio',
'251. Grupo de Categoria - La especialidad es obligatoria  ',
'252. Migración -  Error en flujo de trabajo',
'253. No se genera el recibo de flotantes',
'254. Consulta en proceso',
'255. Los asegurados son requeridos',
'256. Claúsulas: Exclusión de Guerra --  Adicionar - Actualizar',
'257. Encolamiento RS',
'258. cvc-complex-type.2.4.a: Invalid content was found starting with element "Other"',
'259. Claúsulas: Definición de Accidente --  Adicionar - Actualizar',
'260. Este seguro solo aplica para vigencia anual'
  ]
  selectedOption: string = ''
  searchText: string = ''

  get filteredOptions() {
    return this.options.filter(option => option.toLowerCase().includes(this.searchText.toLowerCase()));
  }

  register={
    agrupador_error: '',
    causa_error:'',
    proceso_error:'',
    raizal:'',
    estado_raizal:'',
    responsable: '',
    diagnostico: '',
    accion: '',
    descripsion: '',
    confirmacion: '',
    oc: ''

  }
  onRegister(){
    console.log(this.register)
  }
}
